### ISSUE TITLE
Method overloading in contracts not supported

### ISSUE THREAD

**Issue by frostiq** [dbrainio/Soltsice#16]
When Soltsice tries to generate bindings for contracts with multiple functions with the same name, but with a different set of parameters, it generates invalid TypeScript class with multiple properties with same names. It leads to such compilation error:
```
error TS2300: Duplicate identifier 'transfer'.
```

Desired behavior:
Because TypeScript (afaik) doesn't support method overloading, we can at least choose one function with the biggest set of parameters. So at least it will compile...

If anyone has any other ideas how to resolve this problem, please share it with me and others.

**Comment by buybackoff** [comment]
Truffle-contract is working on this in their web3 1.0 PR, but I do not follow closely the status.
It's simpler to just have different method names.

**Comment by frostiq** [comment]
In my case, I can't change names, because this will breake compatibility with ERC20 or ERC223 (I'm writing a token with 2 transfer functions)

What do you think if we just choose one overloading in TS wrapper, as a temporary solution? I can create a pull request for it, if you agree on this approach.

**Comment by buybackoff** [comment]
Could we check if a method already exists and just add an underscore, e.g. `transfer_`, as a temporary step.

Then I know yet what is the best solution for type signatures when types differ completely, not just args count. Should we generate union types? E.g. `string | number `

**Comment by frostiq** [comment]
We can add underscore in TS wrapper, but web3 doesn't support function overloading anyway, so I don't sure that it will work for now...
Adding union types will be a tricky solution, even if web3 will eventually support it, IMHO.

**Comment by buybackoff** [comment]
https://github.com/trufflesuite/truffle-contract/pull/75
https://github.com/trufflesuite/truffle-contract/pull/94
Both PR propose syntax such as `token.transfer["address,uint256"](...)`, i.e. method lookup by types signature. We won't be able to provide static types with this approach.

We could generate methods as `token.transfer._1(address: string, amount: number | BigNumber)` when there are more than one method, and use the first occurrence as the default. We could pack payload manually and send directly to a contract. This also could be the first step to remove TC as a dependency.

**Comment by buybackoff** [comment]
@frostiq I have fixed the duplicate identifier output by just filtering duplicates. You could always access overloads via untyped `web3`. I will likely not touch this issue with a proper fix before `web3` is 1.0. See commit/release history for details.

**Comment by frostiq** [comment]
@buybackoff, thanks!
I will check this out
